### ISSUE TITLE
Set default segment-url to segments.ligo.org in all utilities

### ISSUE THREAD

**Issue by duncanmmacleod** [ligovirgo/dqsegdb#22]
It would be great to have the default segment URL point to `https://segments.ligo.org` for all DQSegDB utilities. Can this be done?

**Comment by rpfisher** [comment]
Yes, it can.  I do not know why I have not done this before, thanks.

**Comment by duncanmmacleod** [comment]
For the record, it would be great to have this in all `dqsegdb.apicalls` functions as well, not just the command-line executables.

**Comment by robertbruntz** [comment]
The first phase of this will simply be modifying function/method definitions, such as from:
`def dqsegdbCheckVersion(protocol,server,ifo,name,version,warnings=True):`
to:
`dqsegdbCheckVersion(ifo,name,version,warnings=True,protocol="https",server="segments.ligo.org"):`
or maybe:
`dqsegdbCheckVersion(ifo,name,version,warnings=True,protocol=default_protocol,server=default_server):`

We might implement these steps later:
- setting the default protocol and server values (whether implemented separately or together) from the environment variable `DEFAULT_SEGMENT_SERVER`, if that variable is available (and otherwise using `https://segments.ligo.org`)
- combining the `protocol` and `server` parameters into one parameter

**Comment by robertbruntz** [comment]
This issue is being closed because it has been moved to the new repo, here: https://git.ligo.org/computing/dqsegdb/client/-/issues/22
