### ISSUE TITLE
The package glue is not what the setup.py script thinks it is

### ISSUE THREAD

**Issue by duncan-brown** [ligovirgo/dqsegdb#24]
dqsegdb's setup.py script requires a package called ``glue`` but this is 

https://pypi.python.org/pypi/glue

and not the LIGO glue. This means that the install fails with pip.

**Comment by duncanmmacleod** [comment]
@duncan-brown, can you confirm how you are trying to install the `dqsegdb` package as a dependency to `pycbc`?

**Comment by duncan-brown** [comment]
All of PyCBC's other dependencies can be installed with
```
pip install package
```
except for the segment database. You can't upload that to PyPi due to it requiring something that isn't the LSC's glue.

But I think this is a bigger problem that would require fixing the pycbc-glue question.

**Comment by ahnitz** [comment]
@duncanmmacleod What I think we'd like to work is the standard PIP / setuptools methods of dependency resolution. They both rely on PyPI, so this conflict is a bit of an issue. Do you know what benefit requiring 'glue' currently has? The only case I can think of that it won't fail in currently is if 'glue' happens to already be installed. Otherwise, it will pull down the wrong package. In PyCBC we've solved this for ourselves by distributed a pycbc-glue package on PyPI.

**Comment by ahnitz** [comment]
@duncan-brown Yeah, pycbc-glue is not ideal. What I'd like to see (but can't really commit a lot of time too, sorry....) is glue broken apart and uploaded to pypi, so we can depend on just the sub-packages we need.

**Comment by duncanmmacleod** [comment]
thanks @ahnitz, @duncan-brown. I'm pretty sure there is no way for `dqsegdb` to accurately catalogue its dependency on `glue` in such a way that guarantees that you will get `glue` from LSCSoft.

However, since the dependency on glue is a _runtime_ dependency, rather than an install-time dependency, we may be able to relegate the `glue` declaration from `install_requires` to just `requires`, which means `pip install dqsegdb` won't actually try to install it (as far as I can remember).

Additionally, `dqsegdb` should supply a requirements.txt file that outlines the relevant dependencies, and can use a full URL to `http://software.ligo.org/lscsoft/source/glue-X.Y.Z.tar.gz`.

Presumably (just for clarity's sake) you are actually calling `pip install https://url/to/dqsegdb.tar.gz` rather than having it registered on pypi?

**Comment by duncanmmacleod** [comment]
@rpfisher, does #26 resolve this issue?

**Comment by duncan-brown** [comment]
https://github.com/ligovirgo/dqsegdb/pull/26 means that we can pull from the offical repo, so thi is solved by documentation for now. See https://github.com/ligo-cbc/pycbc/pull/1377
