### ISSUE TITLE
Can dqsegdbCheckVersion be removed?

### ISSUE THREAD

**Issue by duncanmmacleod** [ligovirgo/dqsegdb#48]
The `dqsegdb.apicalls.dqsegdbCheckVersion` function is broken, and has been for 4 years. Rather than fixing it, this begs the question, can it just be removed?

https://github.com/ligovirgo/dqsegdb/blob/1c3bea313f707c9270d02dc599b123379c37a41c/dqsegdb/apicalls.py#L47-L84

**Comment by robertbruntz** [comment]
There is a typo in the code, quoted above.  Line 74: `ult_json=json.loads(result)` should be `result_json=json.loads(result)`.

This is fixed in the newest version of the code (being worked on right now; to be uploaded soon).  An example, of the modified code, run from Python 3:

\>>> import dqsegdb
\>>> import dqsegdb.apicalls
\>>> dqsegdb.apicalls.dqsegdbCheckVersion(protocol="http",server="segments.ldas.cit",ifo="L1",name="DMT-SCIENCE",version=1)
True
\>>> dqsegdb.apicalls.dqsegdbCheckVersion(protocol="http",server="segments.ldas.cit",ifo="L1",name="DMT-SCIENCE",version=2)
False
\>>> dqsegdb.apicalls.dqsegdbCheckVersion(protocol="http",server="segments.ldas.cit",ifo="L1",name="DMT-SCIENCE",version="1")
False

Note that unlike what the internal documentation above says (line 62), a string for the version does *not* return the correct result (always False), as can be seen in this test, which is identical in Python 2 and 3:

\>>> a=[1]
\>>> b="1"
\>>> b in a
False
\>>> int(b) in a
True

The code in apicalls.py (equivalent to line 76 in above) has been modified to `if int(version) in version_list:`.

Note also that the `dqsegdb` code base does not currently have any code that calls that method (i.e., `grep -rn --exclude={*.html,*.js,*.pickle,*.doctree,*.pyc} dqsegdbCheckVersion .` from the cloned `dqsegdb` repo returns only the function definition).
